# This file was generated by GoReleaser. DO NOT EDIT.
class Ky < Formula
  desc "A kubernetes yaml swiss army knife."
  homepage "https://github.com/hornpolish/ky"
  version "0.9.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hornpolish/ky/releases/download/v0.9.6/ky_0.9.6_Darwin_x86_64.tar.gz"
    sha256 "43ecf1d8c87dde3d1fd7a607e6f29dfad59f00d28b583bec14f2c001ba3398d2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hornpolish/ky/releases/download/v0.9.6/ky_0.9.6_Linux_x86_64.tar.gz"
      sha256 "9dfdd14dbd6176e6c5fd3225d483aeb18211157164f198f5372f910926fb3cc3"
    end
  end

  def install
    bin.install "ky"
  end

  test do
    system "#{bin}/ky version"
  end
end
