# This file was generated by GoReleaser. DO NOT EDIT.
class Ky < Formula
  desc "A kubernetes yaml swiss army knife."
  homepage "https://github.com/hornpolish/ky"
  version "0.9.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hornpolish/ky/releases/download/v0.9.5/ky_0.9.5_Darwin_x86_64.tar.gz"
    sha256 "742d66c3057e340da1fd1fcde11a4792d6fd52b862e50aa1b766bb81423ad1f9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hornpolish/ky/releases/download/v0.9.5/ky_0.9.5_Linux_x86_64.tar.gz"
      sha256 "0cb660f108ec29786f6352b4b4d042b40abb4cbd50a1bd67bbc207d3dfbe6b05"
    end
  end

  def install
    bin.install "ky"
  end

  test do
    system "#{bin}/ky version"
  end
end
