# This file was generated by GoReleaser. DO NOT EDIT.
class Ky < Formula
  desc "A kubernetes yaml swiss army knife."
  homepage "https://github.com/hornpolish/ky"
  version "0.9.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hornpolish/ky/releases/download/0.9.7/ky_0.9.7_Darwin_x86_64.tar.gz"
    sha256 "bc94dbf145d64d8465dccb01b2cdc748d421b8c4e7cf703a58c43e899a651f23"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hornpolish/ky/releases/download/0.9.7/ky_0.9.7_Linux_x86_64.tar.gz"
      sha256 "4282effe541e588004c885220a748d0d1b69d04acff77a20b9cebb9ad16b012b"
    end
  end

  def install
    bin.install "ky"
  end

  test do
    system "#{bin}/ky version"
  end
end
